[package]
name = "i18n-puzzles"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.1"
clap = { version = "4.5.32", features = ["derive"] }
encoding = "0.2.33"
itertools = "0.14.0"
nom = "8.0.0"
paste = "1.0.15"
regex = "1.11.1"
