[package]
name = "i18n-puzzles"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.32", features = ["derive"] }
itertools = "0.14.0"
paste = "1.0.15"
regex = "1.11.1"
